### ISSUE TITLE
Huge lags, cardboard not working, memory leaks in 0.9.0

### ISSUE THREAD

**Issue by uranpro** [googlevr/gvr-ios-sdk#115] opened 2016-09-01 15:24 UTC
**Huge lags**

When I play ~5 videos in 1 GVRVideoView its start lagging very hard.

**Cardboard not working**

Trying to resolve lags(1) I start creating videoView for each URL. Cardboard working fine only first time, next tries will show black screen. I think there is a memory leaks...

**Memory leaks in 0.9.0**

When I saw cardboard problems(2), I checked GVRVideoView for memory leaks:

1) create GVRVideoView and load some video from URL
2) wait until video starts
3) remove GVRVideoView from superview
4) GVRVideoView is not deallocated (can see in profiler Instruments->Leaks)

```
// ...
@property (nonatomic, strong) GVRVideoView *videoView;
// ...

- (void)viewDidLoad {
    [super viewDidLoad];
    
    [self createVideoView];
}

- (void)createVideoView {
    if (self.videoView) {
        [self.videoView removeFromSuperview];
        [self setVideoView:nil];
    }

    self.videoView = [[GVRVideoView alloc] initWithFrame:CGRectZero];
    self.videoView.delegate = self;
    self.videoView.enableTouchTracking = YES;
    self.videoView.enableCardboardButton = YES;
    self.videoView.displayMode = kGVRWidgetDisplayModeEmbedded;
    self.videoView.translatesAutoresizingMaskIntoConstraints = NO;
    
    [self.view addSubview:self.videoView];
    [self.view addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"V:|[_videoView]|"
                                                                      options:NSLayoutFormatDirectionLeadingToTrailing
                                                                      metrics:nil
                                                                        views:NSDictionaryOfVariableBindings(_videoView)]];
    [self.view addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"H:|[_videoView]|"
                                                                      options:NSLayoutFormatDirectionLeadingToTrailing
                                                                      metrics:nil
                                                                        views:NSDictionaryOfVariableBindings(_videoView)]];
    
    [self.videoView loadFromUrl:[NSURL URLWithString:@"https://xxxxxxx/xxxx.mp4"]];
}

#pragma mark - GVRVideoViewDelegate

- (void)widgetViewDidTap:(GVRWidgetView *)widgetView {
    [self createVideoView];
}
```

**Comment by nathanmartz** [comment] 2016-09-02 15:41
Thanks for the bug report. This is a known issue that we're working on.

**Comment by rainerjungwirth** [comment] 2016-09-03 09:14
You can put the GVRVideoView Object in a singleton Class then you can play multiple videos without issues. The following solutions in swift is working for me

`class GVFix{
    static var sharedInstance = GVRVideoView()
    private init(){}
}

class GoogleViewController: UIViewController {
  override func viewDidLoad() {
        super.viewDidLoad()
       
           
            GVFix.sharedInstance.resume()
            GVFix.sharedInstance.frame = CGRectMake(0, 0, view.frame.width, view.frame.height)
            GVFix.sharedInstance.enableCardboardButton = false
            GVFix.sharedInstance.enableFullscreenButton = false
            GVFix.sharedInstance.loadFromUrl("https://xxxxxxx/xxxx.mp4", ofType: GVRVideoType.Mono)
            GVFix.sharedInstance.displayMode = GVRWidgetDisplayMode.FullscreenVR
            GVFix.sharedInstance.delegate = self
            view.addSubview(GVFix.sharedInstance)
        }

  override func viewDidDisappear(animated: Bool) {
        super.viewDidDisappear(animated)
        GVFix.sharedInstance.stop()
        GVFix.sharedInstance.removeFromSuperview()
}

`

**Comment by r3trosteve** [comment] 2016-09-05 10:00
@rainerjungwirth good shout, this works well for now at least to prevent the crashing I was experiencing time and again....

**Comment by r3trosteve** [comment] 2016-09-05 15:56
Actually, as a follow up, the Singleton approach helps resolve some memory issues (I still get a warning) when rendering the video in the non-cardboard view, but when I switch to cardboard fullscreen mode, my app crashes (on device) with error:

`Message from debugger: Terminated due to memory issue`

**Comment by r3trosteve** [comment] 2016-09-12 22:16
Blush. I killed some UIImage animations and haven't had an issue with the VRView player since.

**Comment by nathanmartz** [comment] 2016-09-12 23:14
Well, glad you got it fixed :)

**Comment by uranpro** [comment] 2016-09-14 09:56
@nathanmartz it fix only cardboard issue! But not huge lags and memory leaks

**Comment by nathanmartz** [comment] 2016-09-17 04:58
Sorry about that. I think at least the leaks will be fixed in our next update. We haven't had as much reproducing the lags.

**Comment by sanjayc77** [comment] 2016-10-11 19:45
Please try the latest GVRSDK 1.0.1.

https://github.com/CocoaPods/Specs/blob/master/Specs/GVRSDK/1.0.1/GVRSDK.podspec.json

**Closed** 2016-10-12 01:33 UTC
