### ISSUE TITLE
Video hang issue after update to iOS SDK version 1.0.1

### ISSUE THREAD

**Issue by anubha-kiwitech** [googlevr/gvr-ios-sdk#140] opened 2016-10-13 04:47 UTC
@sanjayc77 When loading video via a URL, the video hangs after playing initially for few seconds.

**Comment by sanjayc77** [comment] 2016-10-14 22:35
Can you provide more information about this issue?

1. Is it only one specific video or all videos that you tried?
2. Does this happen when the video is played from the local resource?
3. Does this happen with the "congo.mp4" video included as part of the SDK? Try the snippet in the VideoWidgetDemo sample app:

`// Load the sample 360 video, which is of type stereo-over-under.
  //NSString *videoPath = [[NSBundle mainBundle] pathForResource:@"congo" ofType:@"mp4"];
  //[_videoView loadFromUrl:[[NSURL alloc] initFileURLWithPath:videoPath]
  //                 ofType:kGVRVideoTypeStereoOverUnder];
  NSURL *videoUrl = [NSURL URLWithString:@"https://raw.githubusercontent.com/googlevr/gvr-ios-sdk/master/Samples/VideoWidgetDemo/resources/congo.mp4"];
  [_videoView loadFromUrl:videoUrl ofType:kGVRVideoTypeStereoOverUnder];`

**Comment by anubha-kiwitech** [comment] 2016-10-17 05:58
1.Is it only one specific video or all videos that you tried? - All videos
2.Does this happen when the video is played from the local resource? - No
3. Does this happen with the "congo.mp4" video included as part of the SDK? - This doesn't happen with the local congo.mp4 file, but the issue can be replicated with videoURL of congo.mp4 shared in your comments.

**Comment by sanjayc77** [comment] 2016-10-20 18:42
We have identified an issue, introduced in 1.01, where pausing the video also pauses the head tracking (motion tracking). This fix will be in the next release.

Can you verify that this issue does not happen as long as the video is playing?

Thanks

**Comment by freddm** [comment] 2016-10-21 11:36
Hi! I can also confirm that video hangs during loading/buffering. Framerate seems to be lower than previous version (1.0.0). And it's even choppier in fullscreen mode. Any idea when the next release is coming?

**Comment by anubha-kiwitech** [comment] 2016-10-25 08:03
@sanjayc77 I am not pausing the video. I just play the video and after some seconds play the video hangs.

**Comment by sanjayc77** [comment] 2016-10-27 01:49
I am unable to reproduce the hang on the VideoWidgetDemo sample app using a network video url. 

Is this issue happening in your app? Does it also happen in the VideoWidgetDemo sample app?

**Comment by anubha-kiwitech** [comment] 2016-10-28 07:12
@sanjayc77 This is happening in the VideoWidgetDemo sample app too for the version 1.0.1.
The issue can be easily replicated with videoURL of congo.mp4  i.e. "https://raw.githubusercontent.com/googlevr/gvr-ios-sdk/master/Samples/VideoWidgetDemo/resources/congo.mp4"


@freddm  please confirm.

**Comment by freddm** [comment] 2016-10-30 08:53
Video seems to play fine here, but at a lower framerate than before. I am using a HLS stream. The problem I have is that motion/head tracking stops during buffering. I am now using version 1.0.0 because of that problem. But version 1.0.0 leaks memory on iPhone 7, but not on iPhone 6. Strange!

**Comment by sanjayc77** [comment] 2016-10-31 18:52
The issue of head tracking stopping when paused/buffering will be fixed in the next release.

Is the lower frame rate only applicable to HLS stream?

**Comment by freddm** [comment] 2016-11-01 14:14
No, the frame rate problem also exist when playing local video files. Tested on iPhone 6 and 7.

**Comment by skycenter** [comment] 2016-12-01 04:54
Can you upload and show me your update version @ @freedom

**Comment by skycenter** [comment] 2016-12-01 04:55
@freddm

**Comment by skycenter** [comment] 2016-12-01 11:53
![screen shot 2016-12-01 at 3 51 41 am](https://cloud.githubusercontent.com/assets/24266815/20792997/b051c22c-b779-11e6-885e-db991b06a522.png)
 
Whats going on?

**Comment by nathanmartz** [comment] 2016-12-02 03:26
Sky center, if you have an issue please open a new thread for it. Please
don't spam or fork unrelated threads.

**Comment by sanjayc77** [comment] 2017-11-29 23:53
You should switch to [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit). Check out the updated VideoWidgetDemo sample.

Basically, you supply AVPlayer to GVRVideoRenderer and can fully control the playback.

**Closed by sanjayc77** 2017-11-29 23:53 UTC
Labels: bug
