### ISSUE TITLE
Vertical pan gesture

### ISSUE THREAD

**Issue by ecristerna** [googlevr/gvr-ios-sdk#213] opened 2017-02-22 16:24 UTC
Is there a way of getting the vertical pan gesture to work? Right now only horizontal gesture works.

**Comment by MatejBalantic** [comment] 2017-03-02 13:10
+1

**Comment by Neogene** [comment] 2017-04-05 09:05
+1

**Comment by sanjayc77** [comment] 2017-09-02 00:37
Duplicate of #134

**Closed by sanjayc77** 2017-09-02 00:37 UTC
