### ISSUE TITLE
Bug iOS:Get latest update (GVRSDK v1.10.0) and  GVRVideoView makes video green.

### ISSUE THREAD

**Issue by singhdavinder** [googlevr/gvr-ios-sdk#180] opened 2016-12-22 05:21 UTC
I just get latest update of iOS GVRSDK v1.10.0, and GVRVideoView gets green i.e a green layer over my original video for both local and remote URL videos.

**Comment by huynguyencong** [comment] 2016-12-23 06:02
I fixed that problem by add GVRVideoView by code after viewDidAppear.

**Comment by singhdavinder** [comment] 2016-12-23 14:00
@huynguyencong No it does not work

**Comment by huynguyencong** [comment] 2016-12-23 17:29
Oh, sorry, it doesn't like the bug in my application. In my app, it show entire green screen, cannot show video like your app

**Comment by jacobfnl** [comment] 2016-12-30 18:01
This is also plaguing my videos in the 1.10.0 update. Likely the same issue as #172 "GVRVideoView ignores YCbCr matrix information"

**Comment by MarkDKoslow** [comment] 2017-01-19 02:31
I'm running into this same issue as well. Please let us know if there is anything we should try!

**Comment by jacobfnl** [comment] 2017-01-19 02:41
@MarkDKoslow, I was originally using Adobe Media Encoder for exporting my video sequences, and it was attaching this color space yuv420p(tv, bt709). My videos look fine if I encode video using ffmpeg using yuv420p pixel format. More info: https://ffmpeg.org

**Comment by nporteschaikin** [comment] 2017-01-19 21:28
I can confirm this is happening in 1.10.

**Comment by sanjayc77** [comment] 2017-01-21 16:46
This issue will be addressed in the next update. Thanks for reporting.

**Comment by nporteschaikin** [comment] 2017-01-25 15:40
@sanjayc77 Thanks! When do you think this'll be resolved?

**Comment by anuraagdjain** [comment] 2017-01-27 10:54
Is there any way to load video in `stereoOverUnder` mode ?

**Comment by singhdavinder** [comment] 2017-01-27 11:14
@anuraagdjain use "[<GVRVideoViewInstance> loadFromUrl:URL ofType:kGVRVideoTypeStereoOverUnder];"

**Comment by anuraagdjain** [comment] 2017-01-27 11:17
@singhdavinder I've tried that, It's just a blank screen. When I switch to mono, the video plays .

**Comment by singhdavinder** [comment] 2017-01-27 11:24
@anuraagdjain can u show me your code snippet?

**Comment by anuraagdjain** [comment] 2017-01-27 11:36
@singhdavinder  I too get the free overlay sometime, below is my sample code and check the images which I get on the device here : http://imgur.com/a/GkMBa . 

`@IBOutlet weak var videoView: GVRVideoView!`

` guard   let path =  Bundle.main.path(forResource: "360_Degree_Video", ofType: "mp4") else{fatalError()}`
` // let url = URL(string:"https://s3.amazonaws.com/ray.wenderlich/elephant_safari.mp4")`
` let url = URL(fileURLWithPath: path)`
`        videoView.load(from: url, of: .stereoOverUnder)`
  `      videoView.delegate = self`
`        videoView.play()`
  `      videoView.volume = 1.0`
`        videoView.enableTouchTracking = true`
  `      videoView.enableCardboardButton = true`
`        videoView.enableFullscreenButton = true`

**Comment by singhdavinder** [comment] 2017-01-27 12:01
@anuraagdjain  call "videoView.play()"  in "didLoadContent:"  method of "GVRWidgetViewDelegate". And in case you tried to play remote video then again you must have to call "videoView.play()" method explicitly after buffering, this is bug in 1.10.0

**Comment by anuraagdjain** [comment] 2017-02-02 06:45
@singhdavinder I've tried with both local and video URL, the result is still same. Videos don't play in stereo mode and I get purple screen or when I switch from mono to stereo, app hangs. Tried adding videoView.play() is `didLoadContent:`

**Comment by ashishbitcot** [comment] 2017-03-21 14:01
GVRVideoView doesn't show video in cardboard mode and just the black screen, though the audio plays. Can I know what could be the issue. Am using the same code as in the standard VideoWidgetDemo of GoogleVRSDK, just that I have converted it to swift equivalent.

Note: Using GVRSDK 1.10.0

When using higher versions, the video shows but because it is unstable and has lot of issues, specially the stalled playback on buffering, I opted to use 1.10.0, as used in the standard Google example.

Please help, thanks in advance.

**Comment by tibewww** [comment] 2017-04-05 17:02
HI ashishbitcot, did you find a fix for it ?

**Comment by ashishbitcot** [comment] 2017-04-06 05:13
Hey,

Thanks for your response.
The playback looks* very choppy* because of the following issues that are
still prevailing with the GVRSDK iOS latest.

*1. Indication of stalled playback due to running out of buffered video *
https://github.com/googlevr/gvr-ios-sdk/issues/206

- - We can plan to present a loader if we have control over the progress of
the video when it buffers, so the user doesn't experience the stall effect
and         rather is kept informed about the buffering. But currently they
do not have plan to add this.
  *Loading/Buffering indicator* - https://github.com/googlevr/
gvr-ios-sdk/issues/176

*2. Switching between views causes slowdown*
https://github.com/googlevr/gvr-ios-sdk/issues/171

- - It has been added into the internal tracker and can I know the ETA,
will it be closed soon? Please help.


Can it be buffered before hand and then played?

Please let us know if we are missing something, we would be pleased to here
from you and team.


Thanks,
Ashish

**Comment by veerb4h** [comment] 2017-11-13 04:35
@anuraagdjain and @ashishbitcot did you find a fix for it?

**Comment by sanjayc77** [comment] 2017-11-15 05:32
Please migrate to [GVRKit](https://github.com/googlevr/gvr-ios-sdk/tree/master/Samples/GVRKit), available as source code and Cocoapod. It gives you full control of video playback. See the updated VideoWidgetDemo sample.

VR View widgets are not deprecated.

**Closed by sanjayc77** 2017-11-15 05:32 UTC

**Comment by veerb4h** [comment] 2017-11-15 06:55
@sanjayc77 I check out this demo it work with Objective C and display black screen when using swift4, how to solved this swift environment issue
