### ISSUE TITLE
Touch issue in GVRPanoramaView.

### ISSUE THREAD

**Issue by haihoang88** [googlevr/gvr-ios-sdk#158] opened 2016-11-07 11:20 UTC
Hi Google VR team,

I noticed that when we try to touch the Image in GVRPanoramaView (or GVRVideoView), the touch only supports "horizontal" movement. When I try to slide the finger up or down, nothing happens. It kinda hard to describe, I hope you get what I'm trying to say.

Is this the expected behavior, will there be any plan to update the touch support to move up or down?

**Comment by nathanmartz** [comment] 2016-11-07 16:16
Yes, this is a feature we plan to add in an upcoming release. Closing this now as it's a dupe of some other issues here.

**Closed by nathanmartz** 2016-11-07 16:16 UTC
