### ISSUE TITLE
git clone does not compile (undefined symbol _clock_gettime_nsec_np)

### ISSUE THREAD

**Issue by RubenGarcia** [googlevr/gvr-ios-sdk#235] opened 2017-04-05 17:59 UTC
Following 
https://developers.google.com/vr/ios/get-started
git cloned today.

GVR iOS SDK v1.20.0
Xcode:Version 7.3.1 (7D1014)
MacOS version: 10.12.3 (16D32)
Target: iPhone 6s Plus (emulator) and iPhone 6s (emulator)
When clicking run in Xcode I get an error:

Undefined symbols for architecture x86_64:
  "_clock_gettime_nsec_np", referenced from:
      base::GetCurrentTimeNanos() in libGVRSDK.a(get_current_time.o)

************full error log follows
Ld /Users/di29qiq2/Library/Developer/Xcode/DerivedData/TreasureHunt-bctfdirftjblgocecdaemfrmdomh/Build/Products/Debug-iphonesimulator/TreasureHunt.app/TreasureHunt normal x86_64
    cd /Users/di29qiq2/VR/gvr-ios-sdk/Samples/TreasureHunt
    export IPHONEOS_DEPLOYMENT_TARGET=9.2
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -L/Users/di29qiq2/Library/Developer/Xcode/DerivedData/TreasureHunt-bctfdirftjblgocecdaemfrmdomh/Build/Products/Debug-iphonesimulator -L/Users/di29qiq2/Library/Developer/Xcode/DerivedData/TreasureHunt-bctfdirftjblgocecdaemfrmdomh/Build/Products/Debug-iphonesimulator/GTMSessionFetcher -L/Users/di29qiq2/Library/Developer/Xcode/DerivedData/TreasureHunt-bctfdirftjblgocecdaemfrmdomh/Build/Products/Debug-iphonesimulator/GoogleToolboxForMac -L/Users/di29qiq2/VR/gvr-ios-sdk/Samples/TreasureHunt/Pods/GVRSDK/Libraries -F/Users/di29qiq2/Library/Developer/Xcode/DerivedData/TreasureHunt-bctfdirftjblgocecdaemfrmdomh/Build/Products/Debug-iphonesimulator -filelist /Users/di29qiq2/Library/Developer/Xcode/DerivedData/TreasureHunt-bctfdirftjblgocecdaemfrmdomh/Build/Intermediates/TreasureHunt.build/Debug-iphonesimulator/TreasureHunt.build/Objects-normal/x86_64/TreasureHunt.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=9.2 -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -ObjC -lGTMSessionFetcher -lGVRSDK -lGoogleToolboxForMac -lc++ -framework AVFoundation -framework AudioToolbox -framework CoreGraphics -framework CoreMedia -framework CoreMotion -framework CoreText -framework CoreVideo -framework GLKit -framework MediaPlayer -framework OpenGLES -framework QuartzCore -framework Security -fobjc-arc -fobjc-link-runtime -lPods-TreasureHunt -Xlinker -dependency_info -Xlinker /Users/di29qiq2/Library/Developer/Xcode/DerivedData/TreasureHunt-bctfdirftjblgocecdaemfrmdomh/Build/Intermediates/TreasureHunt.build/Debug-iphonesimulator/TreasureHunt.build/Objects-normal/x86_64/TreasureHunt_dependency_info.dat -o /Users/di29qiq2/Library/Developer/Xcode/DerivedData/TreasureHunt-bctfdirftjblgocecdaemfrmdomh/Build/Products/Debug-iphonesimulator/TreasureHunt.app/TreasureHunt

Undefined symbols for architecture x86_64:
  "_clock_gettime_nsec_np", referenced from:
      base::GetCurrentTimeNanos() in libGVRSDK.a(get_current_time.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by michellehardatwork** [comment] 2017-04-10 15:31
Just FYI - I got the same error with Xcode 7.3.1, but it does work when I switch to Xcode 8.2.1.

**Comment by appstute-sayali** [comment] 2017-04-12 04:41
Yes Above error is resolved when I switch to Xcode 8

**Comment by sanjayc77** [comment] 2017-11-29 23:31
Closing this due to age and not reproducible with latest version. Please re-open if the issue still persists.

**Closed by sanjayc77** 2017-11-29 23:31 UTC
