### ISSUE TITLE
question ios 8.0 unity5.3.4p6 xcode7.3.1

### ISSUE THREAD

**Issue by wxpasta** [googlevr/gvr-ios-sdk#27] opened 2016-05-20 07:04 UTC
2016-05-20 11:09:04.498 VRMAX[1982:566634] -> registered mono modules 0x1014a81b8
-> applicationDidFinishLaunching()
May 20 11:09:04  VRMAX[1982] <Error>: CGContextSetShouldAntialias: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
May 20 11:09:04  VRMAX[1982] <Error>: CGContextSetInterpolationQuality: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
May 20 11:09:04  VRMAX[1982] <Error>: CGContextScaleCTM: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
May 20 11:09:04  VRMAX[1982] <Error>: CGContextTranslateCTM: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
May 20 11:09:04  VRMAX[1982] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
May 20 11:09:04  VRMAX[1982] <Error>: CGContextSetBlendMode: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
May 20 11:09:04  VRMAX[1982] <Error>: CGContextSetFillColorWithColor: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
May 20 11:09:04  VRMAX[1982] <Error>: CGContextFillRects: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
2016-05-20 11:09:04.898 VRMAX[1982:566634] Uncaught exception: NSInvalidArgumentException: *** -[NSPlaceholderString initWithFormat:locale:arguments:]: nil argument
(
	0   CoreFoundation                      0x0000000184a91918 <redacted> + 148
	1   libobjc.A.dylib                     0x00000001840fff80 objc_exception_throw + 56
	2   CoreFoundation                      0x0000000184a91848 <redacted> + 0
	3   Foundation                          0x0000000185362814 <redacted> + 124
	4   Foundation                          0x0000000185362710 <redacted> + 68
	5   VRMAX                               0x00000001012ee9cc -[GVROverlayView initWithFrame:] + 3228
	6   VRMAX                               0x00000001012eb588 -[GVRUnityController init] + 104
	7   VRMAX                               0x00000001012ebba0 createUiLayer + 88
	8   VRMAX                               0x000000010067260c -[CardboardAppController createUnityView] + 108
	9   VRMAX                               0x000000010049a140 -[UnityAppController application:didFinishLaunchingWithOptions:] + 1044
	10  UIKit                               0x00000001897f9704 <redacted> + 400
	11  UIKit                               0x0000000189a28130 <redacted> + 2904
	12  UIKit                               0x0000000189a2c4b8 <redacted> + 1672
	13  UIKit                               0x0000000189a295c0 <redacted> + 168
	14  FrontBoardServices                  0x0000000186047790 <redacted> + 184
	15  FrontBoardServices                  0x0000000186047b10 <redacted> + 56
	16  CoreFoundation                      0x0000000184a48efc <redacted> + 24
	17  CoreFoundation                      0x0000000184a48990 <redacted> + 540
	18  CoreFoundation                      0x0000000184a46690 <redacted> + 724
	19  CoreFoundation                      0x0000000184975680 CFRunLoopRunSpecific + 384
	20  UIKit                               0x00000001897f2580 <redacted> + 460
	21  UIKit                               0x00000001897ecd90 UIApplicationMain + 204
	22  VRMAX                               0x00000001009db7f0 main + 208
	23  libdyld.dylib                       0x00000001845168b8 <redacted> + 4
)
2016-05-20 11:09:04.899 VRMAX[1982:566634] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSPlaceholderString initWithFormat:locale:arguments:]: nil argument'
*** First throw call stack:
(0x184a91900 0x1840fff80 0x184a91848 0x185362814 0x185362710 0x1012ee9cc 0x1012eb588 0x1012ebba0 0x10067260c 0x10049a140 0x1897f9704 0x189a28130 0x189a2c4b8 0x189a295c0 0x186047790 0x186047b10 0x184a48efc 0x184a48990 0x184a46690 0x184975680 0x1897f2580 0x1897ecd90 0x1009db7f0 0x1845168b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by sanjayc77** [comment] 2016-05-21 00:27
This is caused by GVROverlayView unable to load a localized string from the resource bundle. Make sure you have CardboadSDK.bundle included and loaded in the Unity app.

**Comment by dav-cz** [comment] 2016-08-06 01:03
Closing this. Please reopen if needed.

**Closed by dav-cz** 2016-08-06 01:03 UTC
