### ISSUE TITLE
Cannot use GVRCardboardView and GVRVideoView in same application

### ISSUE THREAD

**Issue by bubbakanoosh47** [googlevr/gvr-ios-sdk#189] opened 2017-01-24 16:03 UTC
When switching to the new Cocoa Pod 1.10.0 from 1.0.1 and using the pod "GVRSDK" or "GVRSDK/GVRView", I was unable to use a GVRCardboardView. However, if I switched the pod to "GVRSDK/SDK" as shown in the TreasureHunt example then I was no longer able to use the GVRVideoView widget. 

I would like to use both views in my application as the GVRVideoView is much easier to work with but can resort to using purely the GVRCardboardView if that is the direction this SDK is going in.

Currently I am using a Bridging Header to create a Swift 3.0 application with this SDK in Xcode 8.

**Comment by sanjayc77** [comment] 2017-01-24 21:59
Duplicate of #163 

This will be fixed in next revision.

**Closed by sanjayc77** 2017-01-24 21:59 UTC
